// Logins
export const LOGIN_EXECUTIVE =  'LOGIN_EXECUTIVE'
export const LOGIN_EXECUTIVE_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_DOCTOR =  'LOGIN_DOCTOR'
export const LOGIN_DOCTOR_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_LAB =  'LOGIN_LAB'
export const LOGIN_LAB_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_PATIENT =  'LOGIN_PATIENT'
export const LOGIN_PATIENT_SUCCESS = 'LOGIN_SUCCESS'

// Logouts
export const LOGOUT_EXECUTIVE = 'LOGOUT_EXECUTIVE'
export const LOGOUT_EXECUTIVE_SUCCESS = 'LOGOUT_EXECUTIVE_SUCCESS'

export const LOGOUT_DOCTOR = 'LOGOUT_DOCTOR'
export const LOGOUT_DOCTOR_SUCCESS = 'LOGOUT_DOCTOR_SUCCESS'

export const LOGOUT_LAB = 'LOGOUT_LAB'
export const LOGOUT_LAB_SUCCESS = 'LOGOUT_LAB_SUCCESS'

export const LOGOUT_PATIENT = 'LOGOUT_PATIENT'
export const LOGOUT_PATIENT_SUCCESS = 'LOGOUT_PATIENT_SUCCESS'


export const API_ERROR = 'LOGIN_API_ERROR'
